version: "3"
services:
  humandesignzone:
    image: node:20-alpine3.17
    volumes:
      - "$PWD/dist:/usr/src/app"
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
    tmpfs:
      - "/tmp"
    command: ["node", "server/index.mjs"]
    ports:
      - 11233:3000
    restart: always